@startuml
'https://plantuml.com/class-diagram

class LottoCoupon {
    - double loanSize
    - double loanLength
    - double interest
    - int initialCost
    - double loanAPRC = interest + initialCost

    + totalCostOfLoan(loanSize, loanLength, loanARPC)
    + totalInterestOfLoan()
    + lowerARPC()
    + shortenLoanLength()
    + getters()
}

@enduml